version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PRODACTION_POSTGRES_USER} 
      POSTGRES_PASSWORD: ${PRODACTION_POSTGRES_PASSWORD}  
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - ./api:/api
      - ./api/vendor/bundle:/api/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: production
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/var/www
      - ./frontend/nginx/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/uumanager.com/fullchain.pem:/etc/nginx/certs/server.crt
      - /etc/letsencrypt/live/uumanager.com/privkey.pem:/etc/nginx/certs/server.key
    depends_on:
      - api  
    volumes_from:
      - api
volumes:
  postgres-data:
    driver: local
